/*
 * SPDX-FileCopyrightText: 2026 Marjose Darang
 * SPDX-License-Identifier: AGPL-3.0
 *
 * Part of Spotlight. Licensed under the GNU Affero General Public License,
 * version 3 only. See the LICENSE file at the repository root for the full terms.
 */
import { ApiProperty } from '@nestjs/swagger';
import {
  IsIn,
  IsNotEmpty,
  IsOptional,
  IsString,
  MaxLength,
} from 'class-validator';

export class OAuthAuthorizeQueryDto {
  @ApiProperty({
    description:
      'PKCE challenge: `BASE64URL(SHA256(code_verifier))`, generated by the client.',
    maxLength: 128,
    example: 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  code_challenge!: string;

  @ApiProperty({
    description:
      'PKCE challenge method. Only `S256` is accepted; `plain` is not offered.',
    enum: ['S256'],
    default: 'S256',
    required: false,
  })
  @IsOptional()
  @IsIn(['S256'])
  code_challenge_method?: string;

  @ApiProperty({
    description:
      'Opaque CSRF value. The client must generate it, send it here, and verify the value the provider returns matches.',
    maxLength: 128,
    example: 'a4f1c2e0-8b3d-4c9a-9f21-7d6e5b0a2c34',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  state!: string;
}
