/*
 * SPDX-FileCopyrightText: 2026 Marjose Darang
 * SPDX-License-Identifier: AGPL-3.0
 *
 * Part of Spotlight. Licensed under the GNU Affero General Public License,
 * version 3 only. See the LICENSE file at the repository root for the full terms.
 */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R401RouteImport } from './routes/401'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as SigninCallbackRouteImport } from './routes/signin_.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SigninCallbackRoute = SigninCallbackRouteImport.update({
  id: '/signin_/callback',
  path: '/signin/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/about': typeof AboutRoute
  '/signin': typeof SigninRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/signin/callback': typeof SigninCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/about': typeof AboutRoute
  '/signin': typeof SigninRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/signin/callback': typeof SigninCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/401': typeof R401Route
  '/about': typeof AboutRoute
  '/signin': typeof SigninRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/signin_/callback': typeof SigninCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/401' | '/about' | '/signin' | '/feed' | '/signin/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/401' | '/about' | '/signin' | '/feed' | '/signin/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/401'
    | '/about'
    | '/signin'
    | '/_authenticated/feed'
    | '/signin_/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R401Route: typeof R401Route
  AboutRoute: typeof AboutRoute
  SigninRoute: typeof SigninRoute
  SigninCallbackRoute: typeof SigninCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/signin_/callback': {
      id: '/signin_/callback'
      path: '/signin/callback'
      fullPath: '/signin/callback'
      preLoaderRoute: typeof SigninCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R401Route: R401Route,
  AboutRoute: AboutRoute,
  SigninRoute: SigninRoute,
  SigninCallbackRoute: SigninCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
